# Generated by Django 5.0.2 on 2024-04-02 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UIAsset', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='image',
            field=models.ManyToManyField(help_text='for thumbnail images', to='UIAsset.image'),
        ),
    ]
