# Generated by Django 5.0.2 on 2024-04-17 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UIAsset', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='slug',
        ),
    ]
